name: Destruction Changes Validation

on: 
  workflow_dispatch: 
  pull_request:
    types: [edited, opened, synchronize, reopened]
jobs:
  check_references:

    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 2
      uses: actions/setup-python@v2
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyGithub
    # You can test your matrix by printing the current Python version
    - name: search code
      env:
          API_KEY: ${{ secrets.ACCESS_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
      run: python checkrefs.py
     
        
      
      
