name: Naming Convention Check
on: 
  pull_request:
    types: [edited, opened, synchronize, reopened]
jobs:
  branch-name-check:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: deepakputhraya/action-branch-name@master
      with:
        regex: 'SFDC-[0-9]+'
        ignore: main, prod, qa, preprod
        min_length: 5
        max_length: -1
        
  # https://github.com/marketplace/actions/pull-request-title-naming-rules
  pull-request-name-check:
    runs-on: ubuntu-latest
    steps:
      - uses: naveenk1223/action-pr-title@master
        with:
          regex: 'SFDC-[0-9]+' # Regex the title should match.
          prefix_case_sensitive: false # title prefix are case insensitive
          min_length: 5
          max_length: -1
