name: Naming Convention Check
on: [push, pull_request]
jobs:
  build:
    name: Checking Branch Naming Convention
    runs-on: 'ubuntu-latest'
    steps:
    - uses: deepakputhraya/action-branch-name@master
      with:
        regex: 'SFDC-[0-9]+' # Regex the branch should match. This example enforces grouping
        allowed_prefixes: 'feature,stable,fix' # All branches should start with the given prefix
        ignore: prod, qa, preprod # Ignore exactly matching branch names from convention
        min_length: 5 # Min length of the branch name
        max_length: 20 # Max length of the branch name
