name: Naming Convention Check
on: [push, pull_request]
jobs:
  branch_name:
    runs-on: ubuntu-latest
    name: Branch Name
    steps:
      - uses: AlbertHernandez/branch-name-action@v1
        with:
          branch_pattern: 'feature|bug|chore|hotfix'
          comment_for_invalid_branch_name: 'Ups! This branch name is not following the standards! You can see them here: link to naming conventions'
          fail_if_invalid_branch_name: 'true'
          ignore_branch_pattern: 'master|qa|prod|pprd'
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
