name: Search For References

on: 
  workflow_dispatch: 

jobs:
  check_references:

    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyGithub
    # You can test your matrix by printing the current Python version
    - name: search code
      env:
          API_KEY: ${{ secrets.GITHUB_TOKEN }}
      run: python checkrefs.py
     
        
      
      
